// <auto-generated />
using System;
using EWeaponRegistry.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EWeaponRegistry.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503190520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.CitizenProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressEncrypted")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumberEncrypted")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("FirstNameEncrypted")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LastNameEncrypted")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PeselEncrypted")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WeaponBookNumberEncrypted")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("citizen_profiles", (string)null);
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.Firearm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Caliber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerCitizenId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCitizenId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("firearms", (string)null);
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.MedicalAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlertType")
                        .HasColumnType("integer");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("PermitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("PermitId");

                    b.ToTable("medical_alerts", (string)null);
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.OwnershipHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirearmId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NewOwnerCitizenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("PreviousOwnerCitizenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransferType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FirearmId");

                    b.HasIndex("NewOwnerCitizenId");

                    b.HasIndex("PreviousOwnerCitizenId");

                    b.ToTable("ownership_histories", (string)null);
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.Permit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxFirearms")
                        .HasColumnType("integer");

                    b.Property<string>("MedicalExamExpiryDateEncrypted")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PermitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PermitType")
                        .HasColumnType("integer");

                    b.Property<string>("PsychologicalExamExpiryDateEncrypted")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedSlots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("PermitNumber")
                        .IsUnique();

                    b.ToTable("permits", (string)null);
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.Promise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FeeAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("PermitId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromiseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("QrToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("PermitId");

                    b.HasIndex("PromiseNumber")
                        .IsUnique();

                    b.HasIndex("QrToken");

                    b.ToTable("promises", (string)null);
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.PromiseApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GeneratedPromiseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermitId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedWeaponType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByOfficerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.HasIndex("GeneratedPromiseId");

                    b.HasIndex("PermitId");

                    b.HasIndex("ReviewedByOfficerId");

                    b.ToTable("promise_applications", (string)null);
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.TransferRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuyerCitizenId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerPeselEncrypted")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FirearmId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerCitizenId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransferType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerCitizenId");

                    b.HasIndex("FirearmId");

                    b.HasIndex("SellerCitizenId");

                    b.ToTable("transfer_requests", (string)null);
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.CitizenProfile", b =>
                {
                    b.HasOne("EWeaponRegistry.Domain.Entities.User", "User")
                        .WithOne("CitizenProfile")
                        .HasForeignKey("EWeaponRegistry.Domain.Entities.CitizenProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.Firearm", b =>
                {
                    b.HasOne("EWeaponRegistry.Domain.Entities.CitizenProfile", "Owner")
                        .WithMany("Firearms")
                        .HasForeignKey("OwnerCitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.MedicalAlert", b =>
                {
                    b.HasOne("EWeaponRegistry.Domain.Entities.CitizenProfile", "Citizen")
                        .WithMany("MedicalAlerts")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EWeaponRegistry.Domain.Entities.Permit", "Permit")
                        .WithMany("MedicalAlerts")
                        .HasForeignKey("PermitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Citizen");

                    b.Navigation("Permit");
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.OwnershipHistory", b =>
                {
                    b.HasOne("EWeaponRegistry.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EWeaponRegistry.Domain.Entities.Firearm", "Firearm")
                        .WithMany("OwnershipHistories")
                        .HasForeignKey("FirearmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EWeaponRegistry.Domain.Entities.CitizenProfile", "NewOwner")
                        .WithMany()
                        .HasForeignKey("NewOwnerCitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWeaponRegistry.Domain.Entities.CitizenProfile", "PreviousOwner")
                        .WithMany()
                        .HasForeignKey("PreviousOwnerCitizenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Firearm");

                    b.Navigation("NewOwner");

                    b.Navigation("PreviousOwner");
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.Permit", b =>
                {
                    b.HasOne("EWeaponRegistry.Domain.Entities.CitizenProfile", "Citizen")
                        .WithMany("Permits")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.Promise", b =>
                {
                    b.HasOne("EWeaponRegistry.Domain.Entities.CitizenProfile", "Citizen")
                        .WithMany("Promises")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EWeaponRegistry.Domain.Entities.Permit", "Permit")
                        .WithMany("Promises")
                        .HasForeignKey("PermitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("Permit");
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.PromiseApplication", b =>
                {
                    b.HasOne("EWeaponRegistry.Domain.Entities.CitizenProfile", "Citizen")
                        .WithMany("PromiseApplications")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EWeaponRegistry.Domain.Entities.Promise", "GeneratedPromise")
                        .WithMany()
                        .HasForeignKey("GeneratedPromiseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EWeaponRegistry.Domain.Entities.Permit", "Permit")
                        .WithMany("PromiseApplications")
                        .HasForeignKey("PermitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EWeaponRegistry.Domain.Entities.User", "ReviewedByOfficer")
                        .WithMany()
                        .HasForeignKey("ReviewedByOfficerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Citizen");

                    b.Navigation("GeneratedPromise");

                    b.Navigation("Permit");

                    b.Navigation("ReviewedByOfficer");
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.Shop", b =>
                {
                    b.HasOne("EWeaponRegistry.Domain.Entities.User", "User")
                        .WithOne("Shop")
                        .HasForeignKey("EWeaponRegistry.Domain.Entities.Shop", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.TransferRequest", b =>
                {
                    b.HasOne("EWeaponRegistry.Domain.Entities.CitizenProfile", "Buyer")
                        .WithMany("TransferRequestsAsBuyer")
                        .HasForeignKey("BuyerCitizenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EWeaponRegistry.Domain.Entities.Firearm", "Firearm")
                        .WithMany("TransferRequests")
                        .HasForeignKey("FirearmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EWeaponRegistry.Domain.Entities.CitizenProfile", "Seller")
                        .WithMany("TransferRequestsAsSeller")
                        .HasForeignKey("SellerCitizenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Firearm");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.CitizenProfile", b =>
                {
                    b.Navigation("Firearms");

                    b.Navigation("MedicalAlerts");

                    b.Navigation("Permits");

                    b.Navigation("PromiseApplications");

                    b.Navigation("Promises");

                    b.Navigation("TransferRequestsAsBuyer");

                    b.Navigation("TransferRequestsAsSeller");
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.Firearm", b =>
                {
                    b.Navigation("OwnershipHistories");

                    b.Navigation("TransferRequests");
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.Permit", b =>
                {
                    b.Navigation("MedicalAlerts");

                    b.Navigation("PromiseApplications");

                    b.Navigation("Promises");
                });

            modelBuilder.Entity("EWeaponRegistry.Domain.Entities.User", b =>
                {
                    b.Navigation("CitizenProfile");

                    b.Navigation("Shop");
                });
#pragma warning restore 612, 618
        }
    }
}
